celebrities = [
    {"name": "Cristiano Ronaldo", "followers": 627, "about": "footballer", "country": "Portugal"},
    {"name": "Lionel Messi", "followers": 504, "about": "footballer", "country": "Argentina"},
    {"name": "Taylor Swift", "followers": 289, "about": "singer-songwriter", "country": "USA"},
    {"name": "Selena Gomez", "followers": 429, "about": "singer-actress", "country": "USA"},
    {"name": "Virat Kohli", "followers": 269, "about": "cricketer", "country": "India"},
    {"name": "Kylie Jenner", "followers": 400, "about": "businesswoman", "country": "USA"},
    {"name": "Dwayne Johnson", "followers": 395, "about": "actor-wrestler", "country": "USA"},
    {"name": "Ariana Grande", "followers": 380, "about": "singer", "country": "USA"},
    {"name": "Zlatan Ibrahimović", "followers": 65, "about": "footballer", "country": "Sweden"},
    {"name": "Billie Eilish", "followers": 115, "about": "singer", "country": "USA"},
    {"name": "Robert Downey Jr.", "followers": 56, "about": "actor", "country": "USA"},
    {"name": "Kartik Aaryan", "followers": 35, "about": "actor", "country": "India"},
    {"name": "Deepika Padukone", "followers": 80, "about": "actress", "country": "India"},
    {"name": "Shraddha Kapoor", "followers": 83, "about": "actress", "country": "India"},
    {"name": "David Beckham", "followers": 86, "about": "footballer", "country": "England"},
    {"name": "MS Dhoni", "followers": 45, "about": "cricketer", "country": "India"},
    {"name": "LeBron James", "followers": 170, "about": "basketball player", "country": "USA"},
    {"name": "Camila Cabello", "followers": 65, "about": "singer", "country": "USA"},
    {"name": "Chris Hemsworth", "followers": 59, "about": "actor", "country": "Australia"},
    {"name": "Narendra Modi", "followers": 96, "about": "politician", "country": "India"},
    {"name": "Zendaya", "followers": 192, "about": "actress", "country": "USA"},
    {"name": "Shakira", "followers": 92, "about": "singer", "country": "Colombia"},
    {"name": "Emma Watson", "followers": 76, "about": "actress", "country": "UK"},
    {"name": "Ranveer Singh", "followers": 45, "about": "actor", "country": "India"},
    {"name": "Rihanna", "followers": 152, "about": "singer", "country": "Barbados"},
    {"name": "Justin Bieber", "followers": 292, "about": "singer", "country": "Canada"},
    {"name": "Shah Rukh Khan", "followers": 45, "about": "actor", "country": "India"},
    {"name": "Katrina Kaif", "followers": 76, "about": "actress", "country": "India"},
    {"name": "BTS", "followers": 79, "about": "music band", "country": "South Korea"},
    {"name": "BLACKPINK", "followers": 91, "about": "music band", "country": "South Korea"},
    {"name": "Lisa", "followers": 102, "about": "singer", "country": "Thailand"},
    {"name": "Jungkook", "followers": 92, "about": "singer", "country": "South Korea"},
    {"name": "Sachin Tendulkar", "followers": 45, "about": "cricketer", "country": "India"},
    {"name": "Elon Musk", "followers": 180, "about": "entrepreneur", "country": "USA"},
    {"name": "Sundar Pichai", "followers": 5, "about": "CEO", "country": "India"},
    {"name": "Jeff Bezos", "followers": 5, "about": "entrepreneur", "country": "USA"},
    {"name": "Hrithik Roshan", "followers": 45, "about": "actor", "country": "India"},
    {"name": "Megan Thee Stallion", "followers": 30, "about": "rapper", "country": "USA"},
    {"name": "Kangana Ranaut", "followers": 9, "about": "actress", "country": "India"}
]
